//
// ArticlesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ArticlesAPI {

    /**
     Get top headlines
     
     - parameter country: (query) Country code (ISO 3166-1 alpha-2) to retrieve headlines for. 
     - parameter category: (query) Category of the news. Allowed values are business, entertainment, general, health, science, sports, and technology. 
     - parameter page: (query) Use this to page through the results if the total results found is greater than the page size 
     - parameter apiKey: (query) Your API key. 
     - returns: HeadlineResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func fetchArticles(country: String, category: NewsCategory, page: Int, apiKey: String) async throws -> HeadlineResponse {
        return try await fetchArticlesWithRequestBuilder(country: country, category: category, page: page, apiKey: apiKey).execute().body
    }

    /**
     Get top headlines
     - GET /top-headlines
     - Retrieve top headlines for a specified country and category.
     - parameter country: (query) Country code (ISO 3166-1 alpha-2) to retrieve headlines for. 
     - parameter category: (query) Category of the news. Allowed values are business, entertainment, general, health, science, sports, and technology. 
     - parameter page: (query) Use this to page through the results if the total results found is greater than the page size 
     - parameter apiKey: (query) Your API key. 
     - returns: RequestBuilder<HeadlineResponse> 
     */
    open class func fetchArticlesWithRequestBuilder(country: String, category: NewsCategory, page: Int, apiKey: String) -> RequestBuilder<HeadlineResponse> {
        let localVariablePath = "/top-headlines"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "country": (wrappedValue: country.encodeToJSON(), isExplode: true),
            "category": (wrappedValue: category.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page.encodeToJSON(), isExplode: true),
            "apiKey": (wrappedValue: apiKey.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HeadlineResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
