//
// HeadlineResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HeadlineResponse: Codable, JSONEncodable, Hashable {

    /** Response status */
    public var status: String?
    /** Total number of results available */
    public var totalResults: Int
    public var articles: [Article]?

    public init(status: String? = nil, totalResults: Int, articles: [Article]? = nil) {
        self.status = status
        self.totalResults = totalResults
        self.articles = articles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case totalResults
        case articles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(totalResults, forKey: .totalResults)
        try container.encodeIfPresent(articles, forKey: .articles)
    }
}

