//
// NewsCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Specific categories for news articles that can be queried. */
public enum NewsCategory: String, Codable, CaseIterable {
    case business = "business"
    case sports = "sports"
    case technology = "technology"
}
